export const ROUTERS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
  },
  USER: {
    HOME: "/",
    ABOUT: "about",
    MENU: "menu",
    NEWS: "news",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    MENU_MANAGEMENT: "/admin/menu-management",
    ADD_MENU_ITEM: "/admin/menu/add-menu-item",
    EDIT_MENU_ITEM: "/admin/menuitems/update/:itemId",
    ORDER: "/admin/select-table",
    ORDER_MANAGER: "/admin/order-manager",
    ORDER_DETAIL: "/admin/order/:orderId",
    RESERVATION: "/admin/reservations",
    MANAGE_TABLES: "/admin/table/manage",
    // SERVING_TABLES: "/admin/table/serving",
    INVENTORY: "/admin/inventory",
    STAFF: "/admin/staffs",
    STAFF_ADD: "/admin/staff/add",
    STAFF_UPDATE: "/admin/staff/update/:id",
    STAFF_SHIFT_ASSIGNMENTS: "/admin/staff/shift-assignments",
    STAFF_REGISTER_SHIFTS: "/staff/register-shift",
    REPORT: "/admin/report",
    SETTING: "/admin/setting",
    CATEGORY_MANAGEMENT: "/admin/category-management",
  },
  NOT_FOUND: "*",
};