export const ROUTERS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
  },
  USER: {
    HOME: "/",
    ABOUT: "about",
    MENU: "menu",
    ALBUM: "/album",
    CONTACT: "/contact",
    RESERVATION: "/reservation",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    MENU_MANAGEMENT: "/admin/menu-management",
    ORDER: "/admin/order",
    TABLE: "/admin/table",
    INVENTORY: "/admin/inventory",
    STAFF: "/admin/staffs",
    STAFF_UPDATE: "/admin/staff/update/:id",
    STAFF_ADD: "/admin/staff/addNew",
    STAFF_DELETED: "/admin/staff/deleted",
    STAFF_SHIFT_ASSIGNMENTS: "/admin/staff/shift-assignments",
    STAFF_REGISTER_SHIFTS: "/staff/register-shift",
    STAFF_ATTEND_ASSIGNMENT: "/staff/attend-assignment",
    REPORT: "/admin/report",
    SETTING: "/admin/setting",
    CATEGORY_MANAGEMENT: "/admin/category-management",
    PAYMENT: "/admin/payment",
  },
  RESULT: {
    PAYMENT_RESULT: "/api/payment/call-back",
  },
  NOT_FOUND: "*",
};
